- name: remove previous docker installs
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: install dependencies for docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: latest
    update_cache: true
  register: install_result
  retries: 50
  delay: 5
  until: install_result is not failed

- name: get architecture
  shell: dpkg --print-architecture
  register: lin_arch

- name: get os codename
  shell: lsb_release -cs
  register: os_codename

- name: get distribution
  set_fact:
    distribution: "{% if ansible_distribution | lower == 'kali' %}debian{% else %}{{ ansible_distribution | lower }}{% endif %}"

- name: add apt-key and repo for docker
  include_role:
    name: apt-key-repo
  vars:
    repo_name: docker
    repo_filename: docker
    repo_location: "https://download.docker.com/linux/{{ distribution | lower }} {% if 'kali' in os_codename.stdout %}bookworm{% else %}{{ os_codename.stdout }}{% endif %} stable"
    key_url: https://download.docker.com/linux/{{ distribution | lower }}/gpg
    extra_deb_options: arch={{ lin_arch.stdout }}

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-pip
    state: latest
    update_cache: true

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest
  ignore_errors: true
