# Proxmox dynamic inventory configuration - For testing
plugin: community.general.proxmox
url: https://192.168.1.47:8006
user: "root@pam"
password: "" #changing in the future. Testing/wip
validate_certs: false
want_facts: true

# Same settings as main config
group_prefix: proxmox_
facts_prefix: proxmox_
vm_status_filter:
  - running
  - stopped

# Group VMs by their tags
keyed_groups:
  - key: proxmox_tags
    prefix: tag
  - key: proxmox_status
    prefix: status
  - key: proxmox_type
    separator: ""
  - key: proxmox_node
    prefix: node

# Compose custom variables
compose:
  ansible_connection: "{{ 'ssh' if proxmox_type == 'qemu' else ('lxc' if proxmox_type == 'lxc' else 'local') }}"
  ansible_user: "{{ 'root' if proxmox_type == 'node' else 'admin' }}"
