---
all:
  hosts:
    pve-test:
      ansible_host: 192.168.1.47
      ansible_user: root
      ansible_ssh_private_key_file: "~/.ssh/proxmox_ansible"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      # Proxmox API connection
      proxmox_node: pve-test
      proxmox_api_user: "root@pam"
      proxmox_api_password: "{{ lookup('file', '~/.ansible/.api_pass') | trim }}"
      proxmox_api_host: "{{ ansible_host }}"
      proxmox_api_port: 8006
      proxmox_verify_ssl: false
