#!/usr/bin/python
# filepath: /home/ubuntu/.ansible/plugins/filter/tailscale_filters.py

def modify_tailscale_hosts(inventory_dict):
    """
    Add ansible_host and other variables to Tailscale hosts.
    """
    if 'all' in inventory_dict and 'children' in inventory_dict['all'] and 'tailscale' in inventory_dict['all']['children']:
        tailscale = inventory_dict['all']['children']['tailscale']
        if 'children' in tailscale:
            for group_name, group_data in tailscale['children'].items():
                if 'hosts' in group_data:
                    for hostname, host_data in group_data['hosts'].items():
                        # The host data already contains the required fields from the combine operation
                        # Just ensure we have ansible_host
                        if 'ip' in host_data and 'ansible_host' not in host_data:
                            host_data['ansible_host'] = host_data['ip']
    return inventory_dict

class FilterModule(object):
    def filters(self):
        return { 
            'modify_tailscale_hosts': modify_tailscale_hosts
        }

---
all:
  children:
    tailscale:
      children:
        active_devices:
          hosts:
            phalanxedge:
              ansible_host: 100.116.96.77
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitcrusher:
              ansible_host: 100.118.160.26
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitloop-standard-pc-i440fx-piix-1996:
              ansible_host: 100.98.197.89
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ-1:
              ansible_host: 100.114.88.124
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ:
              ansible_host: 100.65.156.126
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            chromeos-google-octopus:
              ansible_host: 100.96.215.112
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            clockworkpi:
              ansible_host: 100.114.77.47
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            code-serv:
              ansible_host: 100.112.253.73
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            desktop-6t2mduf:
              ansible_host: 100.113.61.59
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            google-pixel-6a:
              ansible_host: 100.107.229.124
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            homeassistant:
              ansible_host: 100.72.202.45
              tailscale_machine_type: linux
              tailscale_state: idle; offers exit node
              exit_node: True
            iphone:
              ansible_host: 100.103.47.116
              tailscale_machine_type: iOS
              tailscale_state: offline
              exit_node: False
            windeath:
              ansible_host: 100.79.34.40
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            x13s:
              ansible_host: 100.127.62.73
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
        offline_devices:
          hosts:
            phalanxedge:
              ansible_host: 100.116.96.77
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitcrusher:
              ansible_host: 100.118.160.26
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitloop-standard-pc-i440fx-piix-1996:
              ansible_host: 100.98.197.89
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ-1:
              ansible_host: 100.114.88.124
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ:
              ansible_host: 100.65.156.126
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            chromeos-google-octopus:
              ansible_host: 100.96.215.112
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            clockworkpi:
              ansible_host: 100.114.77.47
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            code-serv:
              ansible_host: 100.112.253.73
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            desktop-6t2mduf:
              ansible_host: 100.113.61.59
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            google-pixel-6a:
              ansible_host: 100.107.229.124
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            homeassistant:
              ansible_host: 100.72.202.45
              tailscale_machine_type: linux
              tailscale_state: idle; offers exit node
              exit_node: True
            iphone:
              ansible_host: 100.103.47.116
              tailscale_machine_type: iOS
              tailscale_state: offline
              exit_node: False
            windeath:
              ansible_host: 100.79.34.40
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            x13s:
              ansible_host: 100.127.62.73
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
        exit_nodes:
          hosts:
            phalanxedge:
              ansible_host: 100.116.96.77
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitcrusher:
              ansible_host: 100.118.160.26
              tailscale_machine_type: linux
              tailscale_state: -
              exit_node: False
            bitloop-standard-pc-i440fx-piix-1996:
              ansible_host: 100.98.197.89
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ-1:
              ansible_host: 100.114.88.124
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            champ:
              ansible_host: 100.65.156.126
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            chromeos-google-octopus:
              ansible_host: 100.96.215.112
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            clockworkpi:
              ansible_host: 100.114.77.47
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            code-serv:
              ansible_host: 100.112.253.73
              tailscale_machine_type: linux
              tailscale_state: offline
              exit_node: False
            desktop-6t2mduf:
              ansible_host: 100.113.61.59
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            google-pixel-6a:
              ansible_host: 100.107.229.124
              tailscale_machine_type: android
              tailscale_state: offline
              exit_node: False
            homeassistant:
              ansible_host: 100.72.202.45
              tailscale_machine_type: linux
              tailscale_state: idle; offers exit node
              exit_node: True
            iphone:
              ansible_host: 100.103.47.116
              tailscale_machine_type: iOS
              tailscale_state: offline
              exit_node: False
            windeath:
              ansible_host: 100.79.34.40
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
            x13s:
              ansible_host: 100.127.62.73
              tailscale_machine_type: windows
              tailscale_state: offline
              exit_node: False
