---
- name: Test Proxmox SSH and API Connections
  hosts: pve-test
  gather_facts: yes
  vars:
    api_password: "{{ lookup('file', '~/.ansible/.api_pass') | trim }}"
  
  tasks:
    - name: Check SSH connection
      ping:
      register: ping_result
      
    - name: Display SSH connection status
      debug:
        msg: "SSH Connection: {{ 'SUCCESS' if ping_result is succeeded else 'FAILED' }}"
        
    - name: Get Proxmox API version (using variable from playbook)
      uri:
        url: "https://{{ ansible_host }}:8006/api2/json/version"
        method: GET
        user: "root@pam"
        password: "{{ api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: version_info_from_var
      
    - name: Display API connection status (using variable from playbook)
      debug:
        msg: 
          - "API Connection (using playbook var): SUCCESS"
          - "Proxmox version: {{ version_info_from_var.json.data.version }}"

    - name: Get Proxmox API version (using variable from inventory)
      uri:
        url: "https://{{ proxmox_api_host }}:{{ proxmox_api_port }}/api2/json/version"
        method: GET
        user: "{{ proxmox_api_user }}"
        password: "{{ proxmox_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: version_info_from_inventory
      
    - name: Display API connection status (using variable from inventory)
      debug:
        msg: 
          - "API Connection (using inventory var): SUCCESS"
          - "Proxmox version: {{ version_info_from_inventory.json.data.version }}"
